spring.application.name=sistema_advocacia

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_advocacia
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9a4f2c8d3e7b1a5f6c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c
jwt.expiration=86400000
server.port=8080


